apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant
bases:
- ../base

resources:
- namespace.yaml

configMapGenerator:
- name: home-assistant-config
  behavior: replace
  literals:
  - TZ="Australia/Sydney"

patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames/0
        value: hass.your.domain.name
    target:
      kind: Certificate
      name: home-assistant-prod
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`hass.your.domain.name`)
    target:
      kind: IngressRouteTCP
      name: home-assistant-route
