apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-stg
  namespace: home-assistant
spec:
  secretName: hass-stg-cert
  dnsNames:
    - hass.k3s.example.com
  issuerRef:
    name: letsencrypt-stg
    kind: ClusterIssuer
