apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingressroute.yaml
- statefulset.yaml
- service.yaml
- certificate.yaml
commonLabels:
  app.kubernetes.io/name: home-assistant
  app: home-assistant
configMapGenerator:
- name: home-assistant-config
  literals:
  - TZ="UTC"
